# Generated by Django 4.2.1 on 2023-05-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_aboutmodel_contactmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
        migrations.DeleteModel(
            name='ContactUrlsModel',
        ),
    ]
